stages:
- stage: dev
  displayName: DEV
  jobs:  
  - deployment: deploy
    displayName: Deploy
    pool: self-hosted pool
    environment: 'testAKS'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: HelmDeploy@0
            displayName: Helm Deploy app
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'private connection'
              namespace: 'dev'
              command: upgrade
              chartType: FilePath
              chartPath: '/path/to/chart'
              releaseName: 'release-name'
              valueFile: '/path/to/value/file'
              arguments: '--create-namespace'