stages:
- stage: dev
  displayName: DEV
  jobs:  
  - deployment: deploy
    displayName: Deploy
    pool: self-hosted pool
    environment: 'testAKS'
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - task: Kubernetes@1
            displayName: 'Create a new namespace for the pull request'
            inputs:
              command: apply
              useConfigurationFile: true
              inline: '{ "kind": "Namespace", "apiVersion": "v1", "metadata": { "name": "test" }}'
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceConnection: 'private connection'
              